// Content Publisher backend — the /admin surface for the Avalanche article drip.
//
// GET  /admin/content          -> article list + statuses (+ recent publish runs)
// POST /admin/content/publish  -> dispatch the publish-article workflow for one slug
//
// The list's source of truth is public/data/content-status.json ON MAIN (generated by
// scripts/build-seo-pages.mjs from publish-state.json — drafts included).
//
// It is read through the GitHub CONTENTS API, not raw.githubusercontent.com and not
// autolander.ai. Both of those are CDN-cached (raw sends `cache-control: max-age=300`),
// so for ~5 minutes after a publish commit they keep reporting the just-published article
// as a draft — which made the panel offer "Publish" again on an article that was already
// live. The contents API reflects the commit immediately. raw stays as the fallback for
// the no-token case, where a few stale minutes are the worst outcome available.
//
// Publishing needs a GITHUB_TOKEN Worker secret (fine-grained PAT for the
// autolander-website repo with Actions read/write + Contents read/write). The token
// never reaches the browser; without it the panel is read-only and says so.

const contentRepo = (env) => env.CONTENT_REPO || 'mgarbs/autolander-website';
const WORKFLOW_FILE = 'publish-article.yml';
const SLUG_RE = /^[a-z0-9][a-z0-9-]{2,80}$/;

function ghHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'autolander-admin-worker',
  };
}

const STATUS_PATH = 'public/data/content-status.json';

// Uncached read via the contents API when we have a token; CDN-cached raw otherwise.
async function fetchStatusJson(env) {
  const repo = contentRepo(env);
  const token = env.GITHUB_TOKEN;

  if (token) {
    try {
      const res = await fetch(
        `https://api.github.com/repos/${repo}/contents/${STATUS_PATH}?ref=main`,
        {
          headers: { ...ghHeaders(token), Accept: 'application/vnd.github.raw', 'Cache-Control': 'no-cache' },
          cf: { cacheTtl: 0, cacheEverything: false },
        },
      );
      if (res.ok) return { ok: true, json: await res.json() };
      // Any API hiccup (rate limit, token scope) falls through to raw rather than
      // failing the panel outright.
    } catch { /* fall through to raw */ }
  }

  try {
    const res = await fetch(`https://raw.githubusercontent.com/${repo}/main/${STATUS_PATH}`, {
      headers: { 'Cache-Control': 'no-cache' },
      cf: { cacheTtl: 0, cacheEverything: false },
    });
    if (!res.ok) return { ok: false, httpStatus: res.status };
    return { ok: true, json: await res.json() };
  } catch (err) {
    return { ok: false, message: String(err?.message || err).slice(0, 200) };
  }
}

export async function handleContentList(env) {
  const status = await fetchStatusJson(env);
  if (!status.ok) {
    return {
      status: 502,
      body: {
        ok: false,
        reason: 'status_fetch_failed',
        ...(status.httpStatus ? { httpStatus: status.httpStatus } : {}),
        ...(status.message ? { message: status.message } : {}),
      },
    };
  }
  const statusJson = status.json;

  // Recent publish runs — lets the UI show "publishing…" between dispatch and the
  // status JSON flipping. Requires the token; degrade silently without it.
  let runs = [];
  const token = env.GITHUB_TOKEN;
  if (token) {
    try {
      const runsRes = await fetch(
        `https://api.github.com/repos/${contentRepo(env)}/actions/workflows/${WORKFLOW_FILE}/runs?per_page=15`,
        { headers: ghHeaders(token) },
      );
      if (runsRes.ok) {
        const j = await runsRes.json();
        runs = (j.workflow_runs || []).map((r) => ({
          id: r.id,
          title: r.display_title || r.name || '',
          status: r.status,            // queued | in_progress | completed
          conclusion: r.conclusion,    // success | failure | cancelled | null
          createdAt: r.created_at,
          url: r.html_url,
        }));
      }
    } catch { /* runs are best-effort */ }
  }

  return {
    status: 200,
    body: {
      ok: true,
      canPublish: Boolean(token),
      generatedAt: statusJson.generatedAt || null,
      articles: Array.isArray(statusJson.articles) ? statusJson.articles : [],
      runs,
    },
  };
}

export async function handleContentPublish(request, env) {
  const token = env.GITHUB_TOKEN;
  if (!token) {
    return {
      status: 503,
      body: {
        ok: false,
        reason: 'publish_disabled',
        message: 'Set the GITHUB_TOKEN Worker secret (repo Actions dispatch access) to enable one-click publishing.',
      },
    };
  }
  let body = {};
  try { body = await request.json(); } catch { /* empty */ }
  const slug = typeof body.slug === 'string' ? body.slug.trim() : '';
  if (!SLUG_RE.test(slug)) {
    return { status: 400, body: { ok: false, reason: 'invalid_slug' } };
  }
  const res = await fetch(
    `https://api.github.com/repos/${contentRepo(env)}/actions/workflows/${WORKFLOW_FILE}/dispatches`,
    {
      method: 'POST',
      headers: { ...ghHeaders(token), 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: 'main', inputs: { slug } }),
    },
  );
  if (res.status === 204) {
    return { status: 202, body: { ok: true, slug, message: 'Publish workflow dispatched — live in ~2-3 minutes.' } };
  }
  const text = await res.text().catch(() => '');
  return {
    status: 502,
    body: { ok: false, reason: 'dispatch_failed', httpStatus: res.status, message: text.slice(0, 300) },
  };
}
