// Content Publisher backend — the /admin surface for the Avalanche article drip.
//
// GET  /admin/content          -> article list + statuses (+ recent publish runs)
// POST /admin/content/publish  -> dispatch the publish-article workflow for one slug
//
// The list's source of truth is public/data/content-status.json ON MAIN (generated by
// scripts/build-seo-pages.mjs from publish-state.json — drafts included). It is read
// from raw.githubusercontent.com rather than autolander.ai so a freshly pushed publish
// shows up without fighting the site CDN's cache.
//
// Publishing needs a GITHUB_TOKEN Worker secret (fine-grained PAT for the
// autolander-website repo with Actions read/write + Contents read/write). The token
// never reaches the browser; without it the panel is read-only and says so.

const contentRepo = (env) => env.CONTENT_REPO || 'mgarbs/autolander-website';
const WORKFLOW_FILE = 'publish-article.yml';
const SLUG_RE = /^[a-z0-9][a-z0-9-]{2,80}$/;

function ghHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'autolander-admin-worker',
  };
}

export async function handleContentList(env) {
  const rawUrl = `https://raw.githubusercontent.com/${contentRepo(env)}/main/public/data/content-status.json`;
  let statusJson = null;
  try {
    const res = await fetch(rawUrl, {
      headers: { 'Cache-Control': 'no-cache' },
      cf: { cacheTtl: 0, cacheEverything: false },
    });
    if (!res.ok) {
      return { status: 502, body: { ok: false, reason: 'status_fetch_failed', httpStatus: res.status } };
    }
    statusJson = await res.json();
  } catch (err) {
    return { status: 502, body: { ok: false, reason: 'status_fetch_failed', message: String(err?.message || err).slice(0, 200) } };
  }

  // Recent publish runs — lets the UI show "publishing…" between dispatch and the
  // status JSON flipping. Requires the token; degrade silently without it.
  let runs = [];
  const token = env.GITHUB_TOKEN;
  if (token) {
    try {
      const runsRes = await fetch(
        `https://api.github.com/repos/${contentRepo(env)}/actions/workflows/${WORKFLOW_FILE}/runs?per_page=15`,
        { headers: ghHeaders(token) },
      );
      if (runsRes.ok) {
        const j = await runsRes.json();
        runs = (j.workflow_runs || []).map((r) => ({
          id: r.id,
          title: r.display_title || r.name || '',
          status: r.status,            // queued | in_progress | completed
          conclusion: r.conclusion,    // success | failure | cancelled | null
          createdAt: r.created_at,
          url: r.html_url,
        }));
      }
    } catch { /* runs are best-effort */ }
  }

  return {
    status: 200,
    body: {
      ok: true,
      canPublish: Boolean(token),
      generatedAt: statusJson.generatedAt || null,
      articles: Array.isArray(statusJson.articles) ? statusJson.articles : [],
      runs,
    },
  };
}

export async function handleContentPublish(request, env) {
  const token = env.GITHUB_TOKEN;
  if (!token) {
    return {
      status: 503,
      body: {
        ok: false,
        reason: 'publish_disabled',
        message: 'Set the GITHUB_TOKEN Worker secret (repo Actions dispatch access) to enable one-click publishing.',
      },
    };
  }
  let body = {};
  try { body = await request.json(); } catch { /* empty */ }
  const slug = typeof body.slug === 'string' ? body.slug.trim() : '';
  if (!SLUG_RE.test(slug)) {
    return { status: 400, body: { ok: false, reason: 'invalid_slug' } };
  }
  const res = await fetch(
    `https://api.github.com/repos/${contentRepo(env)}/actions/workflows/${WORKFLOW_FILE}/dispatches`,
    {
      method: 'POST',
      headers: { ...ghHeaders(token), 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: 'main', inputs: { slug } }),
    },
  );
  if (res.status === 204) {
    return { status: 202, body: { ok: true, slug, message: 'Publish workflow dispatched — live in ~2-3 minutes.' } };
  }
  const text = await res.text().catch(() => '');
  return {
    status: 502,
    body: { ok: false, reason: 'dispatch_failed', httpStatus: res.status, message: text.slice(0, 300) },
  };
}
