// Publish one Avalanche article: flip its publish-state entry, regenerate the static
// silos, and record the URLs that changed for IndexNow and blog verification.
//
//   node scripts/publish-article.mjs <slug>            # flip + regenerate
//   node scripts/publish-article.mjs <slug> --dry-run  # validate and show the target

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  SILOS, articlePath, articleUrl, backlinkedFrom, blogInboundTargets, isPublished, relatedForArticle,
} from './seo/articles/article-system.mjs';
import { SITE, NAV } from './seo/registry.mjs';
import { DRIP_ARTICLES } from './seo/articles/drip-articles.mjs';
import { loadBlogPosts } from './seo/articles/blog-loader.mjs';
import { buildValidationContext, validatePost } from './blog/validate-post.mjs';

const MODULE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SLUG_RE = /^[a-z0-9][a-z0-9-]{2,80}$/;
const STATIC_ARTICLE_CONTENT = DRIP_ARTICLES;

function workflowError(message, exitCode = 1) {
  const error = new Error(message);
  error.exitCode = exitCode;
  return error;
}

export function assertPublishable(content, { root = MODULE_ROOT, context } = {}) {
  if (content?.silo !== 'blog') return { ok: true, errors: [] };
  const validationContext = context || buildValidationContext({ root, selfSlug: content.slug });
  const result = validatePost(content, validationContext, { selfSlug: content.slug });
  if (!result.ok) {
    const error = workflowError(`blog post failed authoritative validation:\n${result.errors.join('\n')}`);
    error.validationErrors = result.errors;
    throw error;
  }
  return result;
}

export function changedUrlsFor(content, articles, state, { publicDir = resolve(MODULE_ROOT, 'public') } = {}) {
  const silo = content && typeof content === 'object' ? SILOS[content.silo] : null;
  const hubKeys = silo
    ? [...new Set([...(silo.augmentKeys || []), ...(content.augmentKeys || [])])]
    : [];
  const backlinks = content && typeof content === 'object'
    ? backlinkedFrom(content.slug, articles)
      .filter((otherSlug) => isPublished(state, otherSlug))
      .map((otherSlug) => articles.find((article) => article.slug === otherSlug))
      .filter(Boolean)
    : [];
  const blogUrls = content?.silo === 'blog'
    ? [
      SITE.origin + NAV.blog.path,
      `${SITE.origin}/blog/feed.xml`,
      ...blogInboundTargets(content, articles, state).map((article) => articleUrl(article)),
    ]
    : [];
  // A clustered silo (aeoGeo) also re-pings the published siblings whose "Keep exploring"
  // list now shows this article, and the blog index, whose "Guides and playbooks" section lists
  // every published guide. Other silos keep their existing URL set.
  const clustered = Boolean(silo?.clusters && content?.cluster);
  const siblingUrls = clustered
    ? articles
      .filter((article) => article.slug !== content.slug && article.silo === content.silo
        && isPublished(state, article.slug)
        && relatedForArticle(article, articles, state).some((link) => link.href === articlePath(content)))
      .map((article) => articleUrl(article))
    : [];
  // A silo whose articles are listed on a NAV page's guides block (aeoGeo: the money page's "AEO and
  // GEO guides for dealers", regenerated by this publish's build) re-pings that page too.
  const guidesUrls = silo?.guidesOn && NAV[silo.guidesOn] ? [SITE.origin + NAV[silo.guidesOn].path] : [];

  const pages = [...new Set([
    articleUrl(content),
    ...hubKeys.map((key) => SITE.origin + NAV[key].path),
    ...guidesUrls,
    ...(content?.silo === 'compare' ? [SITE.origin + '/compare/'] : []),
    ...(content?.alsoOnCompetitors || []).map((competitor) => `${SITE.origin}/compare/${competitor}/`),
    ...backlinks.map((article) => articleUrl(article)),
    ...siblingUrls,
    ...(clustered ? [SITE.origin + NAV.blog.path] : []),
    ...blogUrls,
    SITE.origin + '/',
  ])];
  // The agent layer changes with the HTML: each changed page's Markdown twin (the article's own twin
  // is written by this publish's build; others only if they exist) and both llms files.
  const twinOf = (url) => {
    const path = new URL(url).pathname;
    return path.endsWith('/') ? (path === '/' ? '/index' : path.slice(0, -1)) + '.md' : null;
  };
  const ownTwin = twinOf(articleUrl(content));
  const twins = pages
    .map(twinOf)
    .filter((md) => md && (md === ownTwin || existsSync(resolve(publicDir, md.slice(1)))))
    .map((md) => SITE.origin + md);
  return [...new Set([
    ...pages,
    ...twins,
    `${SITE.origin}/llms.txt`,
    `${SITE.origin}/llms-full.txt`,
    // agents.md lists the published guides of a silo shown on a NAV page (aeoGeo).
    ...(guidesUrls.length ? [`${SITE.origin}/agents.md`] : []),
  ])];
}

function articlesAt(root) {
  const blogDirectory = resolve(root, 'scripts', 'seo', 'articles', 'blog');
  return [
    ...STATIC_ARTICLE_CONTENT,
    ...(existsSync(blogDirectory) ? loadBlogPosts(blogDirectory) : []),
  ];
}

export function publishArticle({
  root = MODULE_ROOT,
  slug,
  dryRun = false,
  noBuild = false,
  today = new Date().toISOString().slice(0, 10),
} = {}) {
  if (!SLUG_RE.test(slug || '')) {
    throw workflowError('usage: node scripts/publish-article.mjs <slug> [--dry-run]', 2);
  }

  const statePath = resolve(root, 'scripts', 'seo', 'articles', 'publish-state.json');
  const changedUrlsPath = resolve(root, '.last-publish.json');
  const state = JSON.parse(readFileSync(statePath, 'utf8'));
  if (!(slug in state)) {
    throw workflowError(`[publish] unknown slug "${slug}". Known slugs:\n  ${Object.keys(state).join('\n  ')}`, 2);
  }

  const articles = articlesAt(root);
  const content = articles.find((article) => article.slug === slug);
  if (!content) throw workflowError(`[publish] content is missing for known slug "${slug}"`, 2);
  assertPublishable(content, { root });

  const already = state[slug].status === 'published';
  const publishedAt = already ? state[slug].publishedAt : today;
  if (dryRun) {
    console.log(`[dry-run] would ${already ? `re-generate (already published ${publishedAt})` : 'publish'} ${articleUrl(content)}`);
    return { slug, publishedAt, already, dryRun: true };
  }

  if (!already) {
    state[slug] = { status: 'published', publishedAt };
    writeFileSync(statePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8');
    console.log(`[publish] ${slug} -> published (${publishedAt})`);
  } else {
    console.log(`[publish] ${slug} already published ${publishedAt}; regenerating only`);
  }

  if (!noBuild) {
    execFileSync(process.execPath, [resolve(root, 'scripts', 'build-compare-pages.mjs')], {
      cwd: root,
      stdio: 'inherit',
    });
    execFileSync(process.execPath, [resolve(root, 'scripts', 'build-seo-pages.mjs')], {
      cwd: root,
      stdio: 'inherit',
    });
  }

  const urls = changedUrlsFor(content, articles, state, { publicDir: resolve(root, 'public') });
  const kind = content.silo === 'blog' ? 'blog' : 'drip';
  writeFileSync(changedUrlsPath, `${JSON.stringify({ slug, publishedAt, kind, urls }, null, 2)}\n`, 'utf8');
  console.log(`[publish] changed URLs recorded -> ${changedUrlsPath}\n  ${urls.join('\n  ')}`);
  console.log('[publish] done. Commit generated public files, publish state, and homepage outputs; deploy; then run IndexNow.');
  return { slug, publishedAt, kind, urls, already, dryRun: false };
}

function cliOptions(argv) {
  const rootIndex = argv.indexOf('--root');
  return {
    slug: argv[0],
    dryRun: argv.includes('--dry-run'),
    noBuild: argv.includes('--no-build'),
    root: rootIndex >= 0 && argv[rootIndex + 1] ? resolve(argv[rootIndex + 1]) : MODULE_ROOT,
  };
}

function main() {
  try {
    publishArticle(cliOptions(process.argv.slice(2)));
  } catch (error) {
    console.error(error.message);
    process.exitCode = error.exitCode || 1;
  }
}

const isCli = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isCli) main();
